name: task_management_app

services:
  task_management_app_redis:
    container_name: task_management_app_redis
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    networks:
      - task_management_app_net
    volumes:
      - task_management_app_vol:/var/lib/redis/data

  task_management_app_mongodb:
    container_name: task_management_app_mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - task_management_app_net
    volumes:
      - task_management_app_vol:/var/lib/mongo/data

  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - task_management_app_mongodb
      - task_management_app_redis
    env_file:
      - .env.docker
    networks:
      - task_management_app_net
    volumes:
      - task_management_app_vol:/var/lib/backend/data

networks:
  task_management_app_net:
    driver: bridge

volumes:
  task_management_app_vol:
    driver: local
